### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by angelcalibur** [AOSP-JF-MM/platform_manifest#4]
Hi Marco!
I've find my issu with BL!
when i want to change the alarm tone, device bootloop and impossible to have the device working. same after wiping cache and dalvik.
i have to wipe data, and then flash another time the rom + gapps.

Maybee you can try to make the issu and see if it happen for you (or tester)!

**Comment by smeroni68** [comment]
Issue confirmed...

**Comment by angelcalibur** [comment]
think i'am alone to use alarm with my device! :D

**Comment by angelcalibur** [comment]
Hi! Same issu with the JDCTeam_jdc_jflte-7.0-20161001-ALPHA-CAF release... :(
